# Dependencies

- name: mariadb | install debian dependencies
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_mariadb_dependencies
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: mariadb | install rpm dependencies
  yum: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_mariadb_dependencies
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Package

- name: mariadb | get the key
  apt_key: >
    url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db
    state=present
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: mariadb | add the repository
  copy: >
    content="deb {{ mariadb.repository|default('http://mirror.jmu.edu/pub/mariadb/repo/' + mariadb.version + '/' + ansible_lsb.id.lower()) }} {{ ansible_lsb.codename }} main" 
    dest=/etc/apt/sources.list.d/mariadb.list
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: mariadb | install debian mariadb
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_mariadb
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: mariadb | install rpm mariadb
  yum: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_mariadb
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Configuration

- name: mariadb | create mariadb configuration
  template: >
    src=my.cnf.j2
    dest={{ path_mariadb_conf }}
    owner=root
    group=root
    mode=0644
  sudo: yes
  notify:
    - mariadb-restart
