# Repository

- name: hhvm | add key
  apt_key: >
    url=http://dl.hhvm.com/conf/hhvm.gpg.key
    state=present
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: hhvm | add the repository
  copy: >
    content="deb http://dl.hhvm.com/ubuntu {{ ansible_lsb.codename }} main" 
    dest=/etc/apt/sources.list.d/hhvm.list
  sudo: yes
  when: ansible_os_family == 'Debian'

# Package

- name: hhvm | install debian hhvm nightly
  apt: >
    pkg={{ item }} 
    state=installed
    update_cache=true
    force=yes
  with_items: pkgs_hhvm_nightly
  sudo: yes
  when: ansible_os_family == 'Debian' and hhvm.nightly is defined and hhvm.nightly == 1

- name: hhvm | install debian hhvm
  apt: >
    pkg={{ item }} 
    state=installed
    update_cache=true
    force=yes
  with_items: pkgs_hhvm
  sudo: yes
  when: ansible_os_family == 'Debian' and (hhvm.nightly is not defined or hhvm.nightly == 0)

- name: hhvm | install rpm hhvm
  yum: >
    pkg={{ item }} 
    state=installed
    force=yes
  with_items: pkgs_hhvm
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Symlink to PHP to use `php -v`

- name: hhvm | symlink to php
  shell: ln -s `which hhvm` /usr/local/bin/php
  sudo: yes
