# Package

- name: nginx | install debian hhvm nginx
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=true
    force=yes
  with_items: pkgs_hhvm_nginx
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: nginx | install rpm hhvm nginx
  yum: >
    pkg={{ item }} 
    state=latest
    force=yes
  with_items: pkgs_hhvm_nginx
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']
