- name: sshkeys | set config
  template: >
    src=ssh_config.j2 
    dest=/etc/ssh/ssh_config 
  notify:
    - ssh-restart

- name: sshkeys | set facts
  set_fact: >
    sshkeys_user="{{ 'vagrant' if protobox_env == 'vagrant' else ansible_user_id }}"
    sshkeys_path="/home/{{ 'vagrant' if protobox_env == 'vagrant' else ansible_user_id }}"

# make sure ssh config exists
- name: sshkeys | ensure directory exists
  file: >
    path={{ sshkeys_path }}/.ssh
    owner={{ sshkeys_user }}
    group={{ sshkeys_user }}
    mode=0700
    state=directory

- name: sshkeys | ensure config exists
  template: >
    src=config.j2 
    dest={{ sshkeys_path }}/.ssh/config 
    owner={{ sshkeys_user }} 
    group={{ sshkeys_user }} 
    mode=0600
  notify:
    - ssh-restart

## SSH Authorized Keys

#- name: sshkeys | check for files
#  stat: >
#    path={{ item.file }}
#  with_items: server.ssh.authorized_keys
#  register: sshkeys_files
#  when: server.ssh.authorized_keys is defined and item.file is defined

#- debug: >
#    msg="{{ item.0.name }} - {{ item.1.stat.exists }}"
#  with_together: 
#    - server.ssh.authorized_keys
#    - sshkeys_files.results

#key={{ item.file|default(lookup('file', sshkeys_path + '/.ssh/id_rsa.pub')) }}
- name: sshkeys | add authorized keys from files
  authorized_key: >
    user={{ item.user|default(sshkeys_user) }}
    key="{{ lookup('file', item.file) }}"
    state=present
  sudo: yes
  with_items: server.ssh.authorized_keys
  when: server.ssh.authorized_keys is defined and item.file is defined

- name: sshkeys | add authorized key entries
  authorized_key: >
    user={{ item.user|default(sshkeys_user) }}
    key="{{ item.key }}"
    state=present
  sudo: yes
  with_items: server.ssh.authorized_keys
  when: server.ssh.authorized_keys is defined and item.key is defined

## SSH Private Keys

# copy key files into place
- name: sshkeys | add private keys from files
  shell: >
    cp {{ item.file }} {{ sshkeys_path }}/.ssh/{{ item.file|basename }}
  with_items: server.ssh.private_keys
  sudo: yes
  when: server.ssh.private_keys is defined and item.file is defined

# copy key entries into place
- name: sshkeys | add private keys entries
  shell: >
    echo -e "{{ item.entry }}" >> {{ sshkeys_path }}/.ssh/{{ item.entry|md5 }} &&
    echo -e "\nhost *\n\tIdentityFile '{{ sshkeys_path }}/.ssh/{{ item.entry|md5 }}'" >> {{ sshkeys_path }}/.ssh/config
    creates={{ sshkeys_path }}/.ssh/{{ item.entry|md5 }}
  with_items: server.ssh.private_keys
  sudo: yes
  when: server.ssh.private_keys is defined and item.entry is defined and item.entry

## Known Hosts

#- name: Install known_hosts file
#  copy: src=known_hosts dest=/home/${ansible_ssh_user}/.ssh/known_hosts owner=${ansible_ssh_user} group=${ansible_ssh_user}

#- name: sshkeys | add known hosts to known_hosts file
#  lineinfile: dest=/home/${ansible_ssh_user}/.ssh/known_hosts regexp=^${item.host} line="${item.line}"
#  with_items:
#   - { "host": "github.com", "line": "github.com,207.97.227.239 ssh-rsa 123" }

- name: sshkeys_vagrant | ensure config exists
  template: >
    src=known_hosts.j2 
    dest={{ sshkeys_path }}/.ssh/known_hosts 
    owner={{ sshkeys_user }} 
    group={{ sshkeys_user }} 
    mode=0600
  notify:
    - ssh-restart

- name: sshkeys | add keyscan
  shell: >
    ssh-keyscan github.com >> {{ sshkeys_path }}/.ssh/known_hosts
  sudo: yes

## Copy keys from the filesystem 

- name: sshkeys | copy custom ssh keys
  shell: >
    cp {{ item }} {{ sshkeys_path }}/.ssh/{{ item|basename }}
  with_fileglob: /vagrant/data/ssh/*
  when: protobox_env == 'vagrant' and item|basename not in [ '.gitignore', 'config', 'known_hosts', 'authorized_keys' ]

- name: sshkeys | check if config exists
  stat: > 
    path=/vagrant/data/ssh/config
  register: ssh_config
  when: protobox_env == 'vagrant'

- name: sshkeys | install config entries
  shell: > 
    cat /vagrant/data/ssh/config >> {{ sshkeys_path }}/.ssh/config
  when: protobox_env == 'vagrant' and ssh_config.stat.exists

- name: sshkeys | check if authorized_keys exists
  stat: > 
    path=/vagrant/data/ssh/authorized_keys
  register: ssh_authorized_keys
  when: protobox_env == 'vagrant'

- name: sshkeys | install authorized_keys entries
  shell: > 
    cat /vagrant/data/ssh/authorized_keys >> {{ sshkeys_path }}/.ssh/authorized_keys
  when: protobox_env == 'vagrant' and ssh_authorized_keys.stat.exists

## Correct the Permissions

- name: sshkeys | fix folder permissions
  file: >
    path={{ sshkeys_path }}/.ssh
    owner={{ sshkeys_user }} 
    group={{ sshkeys_user }} 
    mode=0700

- name: sshkeys | fix file permission
  file: >
    path={{ item }}
    owner={{ sshkeys_user }} 
    group={{ sshkeys_user }} 
    mode=0600
  with_fileglob: sshkeys_path + '/.ssh/*'
  when: item|basename not in [ '.gitignore' ]

