- name: modules | download modules
  shell: >
    drush dl -y 
    --destination={{ item.0.path }}/sites/all/modules
    {{ item.0.options.modules|join(' ') }}
    chdir={{ item.0.path }}
  with_together:
    - applications.drupal
    - drush_status.results
  sudo: yes
  when: item.0.install == 1 and item.0.options.modules is defined

- name: modules | enable modules
  shell: >
    drush en -y
    {{ item.0.options.modules|join(' ') }}
    chdir={{ item.0.path }}
  with_together:
    - applications.drupal
    - drush_status.results
  sudo: yes
  when: item.0.install == 1 and item.0.options.modules is defined
