- name: main | add vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: apache.yml

- include: virtualhosts.yml
  when: apache.vhosts is defined

- include: protobox.yml
  when: protobox_env is defined and protobox_env == 'vagrant'
