# need a tool to unzip
- name: application | install unzip
  apt: >
    pkg={{ item }} 
    state=latest
    force=yes
  with_items:
    - unzip
  sudo: yes

- name: application | set facts
  set_fact: >
    lemonstand_package="http://res.lemonstandapp.com/release/lemonstand_installer.zip"
    lemonstand_backend_url="backend"
    lemonstand_config_url="config_tool"
    lemonstand_user_firstname="Master"
    lemonstand_user_lastname="Admin"
    lemonstand_user_email="admin@admin.com"
    lemonstand_user_username="admin"
    lemonstand_user_password="admin"
    lemonstand_default_theme="1"
    lemonstand_default_theme_twig="1"
    lemonstand_demo_data="1"
    lemonstand_encypt_key="encryption"

- name: application | check for installer
  stat: path=/usr/src/lemonstand.zip
  register: lemonstand_installer

- name: application | download package
  get_url: >
    url={{ lemonstand_package }}
    dest=/usr/src/lemonstand.zip
    force=yes
  when: not lemonstand_installer.stat.exists

- name: application | verify install paths
  file: >
    path={{ item.path }}
    state=directory
  with_items: applications.lemonstand
  when: item.install == 1

- name: application | check for installer
  stat: path={{ item.path }}/install.php
  register: lemonstand_install
  with_items: applications.lemonstand

- name: application | extract installer
  command: >
    unzip lemonstand.zip -d {{ item.path }}
    chdir=/usr/src/
    creates={{ item.path }}/install.php
  with_items: applications.lemonstand
  when: item.install == 1

- name: application | add custom installer
  template: >
    src={{ item.installer|default('custominstall.php.j2') }}
    dest={{ item.path }}/custominstall.php
  with_items: applications.lemonstand
  when: item.install == 1

- name: application | run installers
  command: >
    php custominstall.php
    chdir={{ item.path }}
    creates=index.php
  with_items: applications.lemonstand
  when: item.install == 1

#- name: application | remove custom installer
#  file: >
#    path={{ item.path }}/custominstall.php
#    state=absent
#  with_items: applications.lemonstand
#  when: item.install == 1
