#PHP 5.2.5 or higher
#PHP CURL library
#PHP OpenSSL library
#PHP Mcrypt library
#PHP MySQL functions
#PHP Multibyte String functions
#Permissions for PHP to write to the installation directory

- name: compatibility | require php
  fail: msg="PHP is required"
  when: php is not defined or php.install != 1

- name: compatibility | require apache
  fail: msg="Apache is required"
  when: apache is not defined or apache.install != 1

- name: compatibility | require mysql
  fail: msg="Mysql is required"
  when: mysql is not defined or mysql.install != 1

# TODO : run shell or grep against php.ini to check instead of this
#- name: compatibility | check php short tags
#  shell: "php -i | grep -i '^short_open_tag' | awk '{print $3}'"
#  register: php_short_open_tags

# TODO : so using this for now
- name: compatibility | check php short tags
  fail: msg="PHP - short_open_tag is required"
  when: php is not defined or php.ini is not defined or php.ini.short_open_tag is not defined

- name: compatibility | check for install path
  fail: msg="Lemonstand - {{ item.name }} - Install path missing"
  with_items: applications.lemonstand
  when: item.path is not defined

- name: compatibility | check for options
  fail: msg="Lemonstand - {{ item.name }} - Options are missing"
  with_items: applications.lemonstand
  when: item.options is not defined

# Check for license information

- name: compatibility | check for license holder
  fail: msg="Lemonstand - {{ item.name }} - License Holder is missing"
  with_items: applications.lemonstand
  when: item.options.holder is not defined or item.options.holder == ''

- name: compatibility | check for serial
  fail: msg="Lemonstand - {{ item.name }} - Serial is missing"
  with_items: applications.lemonstand
  when: item.options.serial is not defined or item.options.serial == ''
