- name: apache-restart
  service: >
    name={{ service_apache }}
    state=restarted
  sudo: yes

- name: apache-start
  service: >
    name={{ service_apache }} 
    state=started
  sudo: yes

- name: apache-stop
  service: >
    name={{ service_apache }} 
    state=stopped
  sudo: yes
