- name: compatibility | require php
  fail: msg="PHP is required"
  when: >
    (php is not defined or php.install != 1) and
    (hhvm is not defined or hhvm.install != 1)

- name: compatibility | check for install path
  fail: msg="Pyrocms - {{ item.name }} - Install path missing"
  with_items: applications.pyrocms
  when: item.path is not defined

- name: compatibility | check for options
  fail: msg="Pyrocms - {{ item.name }} - Options are missing"
  with_items: applications.pyrocms
  when: item.options is not defined
