- name: nginx-restart
  service: >
    name={{ service_nginx }}
    state=restarted
  sudo: yes

- name: nginx-start
  service: >
    name={{ service_nginx }} 
    state=started
  sudo: yes

- name: nginx-stop
  service: >
    name={{ service_nginx }} 
    state=restarted
  sudo: yes

- name: nginx-reload
  service: >
    name={{ service_nginx }}
    state=reloaded
  sudo: yes