---
vagrantfile-digital_ocean:
    vm:
        box: digital_ocean
        hostname: ChatterJS
        network:
            private_network: 192.168.56.104
            forwarded_port: {  }
        provider:
            digital_ocean:
                image: 'CentOS 6.4 x64'
                region: 'New York 1'
                size: 512MB
                client_id: 65655b94ea4333cb9bf8327d01556d15
                api_key: 0ed6bbe62eb9de2eb00274faa9e9d10a
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            tlJjbqiBQqJC:
                id: webroot
                source: ../../src
                target: /var/www
    ssh:
        host: null
        port: null
        private_key_path: ~/.ssh/id_rsa
        username: dwolf@oncall.local
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim-common
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
nginx:
    install: '1'
    vhosts:
        2mtad6Yggu5I:
            server_name: chatterjs.com
            server_aliases:
                - www.chatterjs.com
            www_root: /var/www/frontend
            listen_port: '80'
            index_files:
                - index.html
php:
    install: '1'
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mbstring
            - mcrypt
        pear: {  }
        pecl:
            - pecl_http
    ini:
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        display_errors: Off
    timezone: America/Chicago
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases:
        zUcTE7ewHLKd:
            grant:
                - ALL
            name: dbname
            host: localhost
            user: dbuser
            password: '123'
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'

