# Package

- name: apache | install debian php apache
  apt: >
    pkg={{ item }} 
    state=installed
  with_items: pkgs_php_apache
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: apache | install rpm php apache
  yum: >
    pkg={{ item }} 
    state=installed
  with_items: pkgs_php_apache
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Configuration

- name: apache | set apache ini 
  template: >
    src=php.ini.j2
    dest=/etc/php5/apache2/php.ini
  sudo: yes
  when: php.ini is defined
  notify:
    - php-restart
