# Packages

- name: composer | install debian dependencies
  apt: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_php_composer
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: composer | install rpm dependencies
  yum: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_php_composer
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Installation

- name: composer | install composer
  shell: >
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f ./composer.phar {{ path_php_composer }}
    creates={{ path_php_composer }}
  sudo: yes
