# Configuration

# php 5.3 does not have php5enmod so manually create it
- name: ini | ensure directory exists
  file: >
    path=/etc/php5/mods-available
    state=directory
    owner=root
    group=root
    mode=0755
  when: php_version_53
