- name: main | add vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: php.yml

- name: main | check version
  shell: php -i | grep 'PHP Version' | head -1
  register: php_version

- name: main | set facts
  set_fact: >
    php_version_53={{ True if '5.3.' in php_version.stdout else False }}
    php_version_54={{ True if '5.4.' in php_version.stdout else False }}
    php_version_55={{ True if '5.5.' in php_version.stdout else False }}

- include: ini.yml

- include: mysql.yml
  when: mysql is defined and mysql.install == 1

- include: mariadb.yml
  when: mariadb is defined and mariadb.install == 1

- include: apache.yml
  when: apache is defined and apache.install == 1

- include: nginx.yml
  when: nginx is defined and nginx.install == 1

- include: pear.yml
  when: php.pear is defined and php.pear.install == 1

- include: pecl.yml
  when: php.pecl is defined and php.pecl.install == 1

- include: apc.yml
  when: php.apc is defined and php.apc.install == 1

- include: composer.yml
  when: php.composer is defined and php.composer.install == 1

- include: phpmyadmin.yml
  when: php.phpmyadmin is defined and php.phpmyadmin.install == 1

- include: mailcatcher.yml
  when: php.mailcatcher is defined and php.mailcatcher.install == 1

- include: xdebug.yml
  when: php.xdebug is defined and php.xdebug.install == 1

- include: xhprof.yml
  when: php.xhprof is defined and php.xhprof.install == 1
