# Package

- name: mysql | install debian php mysql
  apt: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_php_mysql
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: mysql | install rpm php mysql
  yum: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_php_mysql
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']