# Compatibility

- name: xhprof | require pecl
  fail: msg="PHP - Pecl is required"
  when: php.pecl is not defined or php.pecl.install != 1

# Package 

- name: xhprof | install packages
  command: pecl install {{ php.xhprof.package|default('xhprof-beta') }}
  ignore_errors: True

# Configuration

- name: xhprof | set ini 
  template: >
    src=xhprof.ini.j2
    dest=/etc/php5/mods-available/xhprof.ini
  sudo: yes

# php 5.3 does not have php5enmod 
- name: xhprof | enable xhprof config
  shell: >
    chdir=/etc/php5/mods-available
    php5enmod xhprof;
  sudo: yes
  when: not php_version_53
  notify:
    - php-restart

- name: xhprof | enable xhprof config on php 5.3
  file: >
    src=/etc/php5/mods-available/xhprof.ini
    dest=/etc/php5/conf.d/xhprof.ini
    state=link
  when: php_version_53
  notify:
    - php-restart

# TODO: web gui