- name: php-restart
  service: >
    name={{ service_apache }} 
    state=restarted
  sudo: yes
  when: apache is defined and apache.install == 1

- name: php-restart
  service: >
    name={{ service_nginx }} 
    state=restarted
  sudo: yes
  when: nginx is defined and nginx.install == 1

- name: php-fpm-restart
  service: >
    name={{ service_php_fpm }}
    state=restarted
  sudo: yes
