- name: rabbitmq-restart
  service: >
    name={{ service_rabbitmq }}
    state=restarted
  sudo: yes

- name: rabbitmq-start
  service: >
    name={{ service_rabbitmq }}
    state=started
  sudo: yes

- name: rabbitmq-stop
  service: >
    name={{ service_rabbitmq }}
    state=stopped
  sudo: yes
