- name: compatibility | require php
  fail: msg="PHP is required"
  when: php is not defined or php.install != 1

- name: compatibility | require apache or nginx
  fail: msg="Apache or Nginx is required"
  when: (apache is not defined or apache.install != 1) and (nginx is not defined or nginx.install != 1)
