- name: main | add vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: nginx.yml

- include: virtualhosts.yml
  when: nginx.vhosts is defined

- include: protobox.yml
  when: protobox_env is defined and protobox_env == 'vagrant'
