- name: application | check for laravel
  stat: >
    path=/usr/local/bin/laravel
  register: laravel_phar

- name: application | download package
  get_url: >
    url=http://laravel.com/laravel.phar
    dest=/usr/src/laravel.phar
    force=yes
  when: not laravel_phar.stat.exists

- name: application | move package
  command: >
    mv laravel.phar /usr/local/bin/laravel
    chdir=/usr/src/
  sudo: yes
  when: not laravel_phar.stat.exists

- name: application | set permissions
  file: >
    path=/usr/local/bin/laravel
    owner=vagrant
    group=vagrant
    mode=0755
  sudo: yes
  when: not laravel_phar.stat.exists

- name: application | check installation
  stat: >
    path={{ item.path }}
  register: laravel_install
  with_items: applications.laravel

- name: application | verify install paths
  file: >
    path={{ item.0.path|dirname }}
    state=directory
  with_together:
    - applications.laravel
    - laravel_install.results 
  when: item.0.install == 1 and not item.1.stat.exists

- name: application | install laravel
  command: > 
    laravel new {{ item.0.path|basename }}
    chdir={{ item.0.path|dirname }}
  with_together:
    - applications.laravel
    - laravel_install.results 
  sudo: yes
  when: item.0.install == 1 and not item.1.stat.exists

# TODO : set apache + nginx virtual host document root to /public folder or verify it as part of compatibility