- name: dependencies | install dependencies
  apt: >
    pkg={{ item }} 
    state=latest
  with_items:
    - php5-mcrypt
  sudo: yes

# TODO : As of PHP 5.5, some OS distributions may require you to manually install the PHP JSON extension
# 
# Right now, php5-json does not exist as a package, so check to see if it does before installing it
# 
# - php5-json