- name: hhvm-restart
  service: >
    name={{ service_hhvm }}
    state=restarted
  sudo: yes

- name: hhvm-start
  service: >
    name={{ service_hhvm }}
    state=started
  sudo: yes

- name: hhvm-stop
  service: >
    name={{ service_hhvm }}
    state=restarted
  sudo: yes

- name: apache-restart
  service: >
    name={{ service_apache }}
    state=restarted
  sudo: yes