# Dependencies

- name: app | install debian dependencies
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=true
  with_items: pkgs_mysql_dependencies
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: app | install rpm dependencies
  yum: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_mysql_dependencies
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Package

- name: app | install debian postgresql
  apt: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_mysql
  sudo: yes
  when: ansible_os_family == 'Debian'

- name: app | install rpm postgresql
  yum: >
    pkg={{ item }} 
    state=latest
  with_items: pkgs_mysql
  sudo: yes
  when: ansible_os_family in ['CentOS', 'Fedora', 'OpenSuse', 'RedHat']

# Configuration

- name: app | create postgresql configuration
  template: >
    src=postgresql.conf
    dest=/etc/postgresql/{{ postgresql.version }}/main/postgresql.conf
    owner={{ postgresql.user }}
    group={{ postgresql.group }}
    mode=0644
  sudo: yes
  notify:
    - postgresql-restart
