- name: databases | create databases
  sudo_user: {{ postgresql.user|default('postgresql') }}
  postgresql_db: >
    name={{ item.name }}
    encoding={{ item.encoding|default('UTF-8') }}
    lc_collate={{ item.collate|default('en_US.UTF-8') }}
    lc_ctype={{ item.ctype|default('en_US.UTF-8') }}
    template={{ item.template|default('template0') }}
    state=present
  with_items: postgresql.databases
  
#- name: databases | add hstore
#  sudo_user: {{ postgresql.user|default('postgresql') }}
#  shell: psql {{ pg_db }} -c "CREATE EXTENSION IF NOT EXISTS hstore;"
#  when: pg_hstore